name: spg
favicon: null
layout_spectrum: 0.30925542511977255
typography_spectrum: 0.8931760352570564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9981903911102563
  lightness: 0.5069273558910936
  saturation: 0.9021567041054368
  rhythmicContrast: 0.8207655937876552
purpose: []
